import {randomBytes} from 'node:crypto';
import {getCheckout} from '../checkout/service';
import {validateApprovalToken} from '../checkout/approval';
import {PRODUCTS} from '../../app/lib/data';
import {redisSetJson,redisGetJson} from '../db/redis';
import {seal} from '../security/seal';
import {getUser} from '../auth/service';
import {createStripeCheckoutSession} from './stripe';
import {reserveInventory} from '../fulfilment/inventory';
export async function startPayment(input:{checkoutId:string;approvalToken:string;items:{productId:string;quantity:number}[];email:string;userId:string;origin:string}){const c=await getCheckout(input.checkoutId);if(!c||c.state!=='APPROVED'||!c.address)throw new Error('Checkout is not approved for payment.');const valid=await validateApprovalToken(input.approvalToken,{checkoutId:c.checkoutId,attemptId:c.attemptId,addressVersion:c.addressVersion,policyVersion:c.policyVersion});if(!valid)throw new Error('Checkout approval is invalid or expired.');if(!c.userId)throw new Error('An Alvis account is required before payment.');
if(c.userId!==input.userId)throw new Error('This checkout does not belong to the signed-in account.');
const user=await getUser(c.userId);
if(!user?.phoneVerified)throw new Error('Phone verification is required before payment.');
if(user.email.toLowerCase()!==input.email.trim().toLowerCase())throw new Error('Payment customer details do not match the signed-in account.');
const items=input.items.map(i=>{const p=PRODUCTS.find(x=>x.id===i.productId);if(!p||!p.inStock)throw new Error('A product in your cart is unavailable.');if(!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>20)throw new Error('Invalid quantity.');return {productId:p.id,name:p.name,quantity:i.quantity,unitPrice:p.price};});if(!items.length)throw new Error('Your cart is empty.');const total=Number(items.reduce((n,i)=>n+i.quantity*i.unitPrice,0).toFixed(2));const key=`pay:${c.checkoutId}:${c.attemptId}`;const existing=await redisGetJson<any>(key);if(existing?.url)return existing;const lock=await import('../db/redis').then(m=>m.redisCommand<string>('SET',`lock:${key}`,input.attemptId,'NX','EX',120));if(lock!=='OK'){const retry=await redisGetJson<any>(key);if(retry?.url)return retry;throw new Error('Payment is already being prepared. Please retry in a moment.');}let reservationIds:string[]=[];try{reservationIds=await Promise.all(items.map(i=>reserveInventory(i.productId,i.quantity)));const session=await createStripeCheckoutSession({orderId:c.checkoutId,amount:total,email:input.email,successUrl:`${input.origin}/checkout?payment=success&checkout=${c.checkoutId}`,cancelUrl:`${input.origin}/checkout?payment=cancelled&checkout=${c.checkoutId}`,idempotencyKey:randomBytes(16).toString('hex'),items});const draft={checkoutId:c.checkoutId,attemptId:c.attemptId,approvalTokenId:valid.tokenId,reservationIds,sealedApprovalToken:seal(input.approvalToken),items,total,email:input.email,address:c.address,addressVersion:c.addressVersion,stripeSessionId:session.id,createdAt:new Date().toISOString()};await redisSetJson(key,{...draft,url:session.url,id:session.id},3600);await redisSetJson(`stripe_session:${session.id}`,draft,86400);await import('../db/redis').then(m=>m.redisCommand('DEL',`lock:${key}`));return session;}catch(error){for(const id of reservationIds)await import('../fulfilment/inventory').then(m=>m.releaseInventory(id));await import('../db/redis').then(m=>m.redisCommand('DEL',`lock:${key}`));throw error;}}
