import {createHash,createSign,createPublicKey,randomBytes,createVerify} from 'node:crypto';
import {redisGetJson,redisSetJson,redisCommand} from '../db/redis';
import {registerUser,type User} from './service';
export async function oauthState(provider:string,returnTo='/account'){const state=randomBytes(24).toString('base64url');await redisSetJson(`oauth:${provider}:${state}`,{returnTo},600);return state;}
export async function consumeState(provider:string,state:string){const key=`oauth:${provider}:${state}`;const r=await redisGetJson<{returnTo:string}>(key);if(!r)throw new Error('OAuth state expired.');await redisCommand('DEL',key);return r;}
export function googleUrl(state:string){const p=new URLSearchParams({client_id:need('GOOGLE_CLIENT_ID'),redirect_uri:need('GOOGLE_REDIRECT_URI'),response_type:'code',scope:'openid email profile',state,access_type:'online'});return `https://accounts.google.com/o/oauth2/v2/auth?${p}`;}
export function appleUrl(state:string){const p=new URLSearchParams({client_id:need('APPLE_CLIENT_ID'),redirect_uri:need('APPLE_REDIRECT_URI'),response_type:'code',response_mode:'form_post',scope:'name email',state});return `https://appleid.apple.com/auth/authorize?${p}`;}
async function exchange(provider:string,code:string){if(provider==='google'){const body=new URLSearchParams({code,client_id:need('GOOGLE_CLIENT_ID'),client_secret:need('GOOGLE_CLIENT_SECRET'),redirect_uri:need('GOOGLE_REDIRECT_URI'),grant_type:'authorization_code'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Google authentication failed.');const t=await r.json() as any;return verifyOidc(t.id_token,'https://accounts.google.com');}const body=new URLSearchParams({client_id:need('APPLE_CLIENT_ID'),client_secret:await appleClientSecret(),code,grant_type:'authorization_code',redirect_uri:need('APPLE_REDIRECT_URI')});const r=await fetch('https://appleid.apple.com/auth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error('Apple authentication failed.');const t=await r.json() as any;return verifyOidc(t.id_token,'https://appleid.apple.com');}
async function verifyOidc(jwt:string,issuer:string){const [h,p,s]=jwt.split('.');if(!h||!p||!s)throw new Error('Invalid identity token.');const header=JSON.parse(Buffer.from(h,'base64url').toString());const jwks=await (await fetch(`${issuer==='https://appleid.apple.com'?'https://appleid.apple.com/auth/keys':'https://www.googleapis.com/oauth2/v3/certs'}`)).json() as any;const jwk=jwks.keys.find((k:any)=>k.kid===header.kid);if(!jwk)throw new Error('Identity signing key unavailable.');const verify=createVerify(header.alg==='ES256'?'SHA256':'RSA-SHA256');verify.update(`${h}.${p}`);verify.end();const signature=header.alg==='ES256'?rawEcdsaToDer(Buffer.from(s,'base64url')):Buffer.from(s,'base64url');if(!verify.verify(createPublicKey({key:jwk,format:'jwk'}),signature))throw new Error('Invalid identity signature.');const claims=JSON.parse(Buffer.from(p,'base64url').toString());if(claims.iss!==issuer||!claims.email||!claims.aud||claims.exp<=Math.floor(Date.now()/1000))throw new Error('Invalid identity claims.');return {email:String(claims.email).toLowerCase(),name:String(claims.name||claims.email.split('@')[0])};}
async function appleClientSecret(){const key=need('APPLE_PRIVATE_KEY').replace(/\\n/g,'\n');const header=Buffer.from(JSON.stringify({alg:'ES256',kid:need('APPLE_KEY_ID')})).toString('base64url');const payload=Buffer.from(JSON.stringify({iss:need('APPLE_TEAM_ID'),iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+300,aud:'https://appleid.apple.com',sub:need('APPLE_CLIENT_ID')})).toString('base64url');const sign=createSign('SHA256');sign.update(`${header}.${payload}`);sign.end();return `${header}.${payload}.${sign.sign({key: key, dsaEncoding:'ieee-p1363'}).toString('base64url')}`;}
export async function oauthUser(provider:string,code:string){return exchange(provider,code);}
function need(k:string){const v=process.env[k];if(!v)throw new Error(`${k} is not configured.`);return v;}

function rawEcdsaToDer(sig:Buffer){const n=sig.length/2;const enc=(x:Buffer)=>{let y=x;while(y.length>1&&y[0]===0)y=y.subarray(1);if(y[0]&0x80)y=Buffer.concat([Buffer.from([0]),y]);return Buffer.concat([Buffer.from([0x02,y.length]),y]);};const r=enc(sig.subarray(0,n)),s=enc(sig.subarray(n));const len=r.length+s.length;return Buffer.concat([Buffer.from([0x30,len]),r,s]);}
