import {json,redirect} from '@remix-run/node';
import {Form,Link,useActionData,useNavigation} from '@remix-run/react';
import AuthLayout from '~/components/AuthLayout';
import {registerUser} from '../../server/auth/service';
import {createSession} from '../../server/security/session';
import {sessionCookie} from '../../server/security/cookies';
import {issueEmailVerification} from '../../server/auth/email';
export async function action({request}:{request:Request}){const fd=await request.formData();try{const user=await registerUser({name:String(fd.get('name')||''),email:String(fd.get('email')||''),password:String(fd.get('password')||''),consent:fd.get('consent')==='on'});await issueEmailVerification(user);const s=await createSession(user.id);return redirect('/account',{headers:{'Set-Cookie':sessionCookie(s.raw,s.expiresAt)}});}catch(e){return json({error:e instanceof Error?e.message:'Unable to create account.'},{status:400});}}
export default function Register(){const data=useActionData<typeof action>();const nav=useNavigation();return <AuthLayout title="Create Account" subtitle="Your security and consent come first"><Form method="post" className="space-y-4">{data?.error&&<div className="text-red-700 text-sm">{data.error}</div>}<input name="name" required placeholder="Full name" className="w-full px-4 py-3 border rounded-lg"/><input name="email" type="email" required placeholder="Personal email" className="w-full px-4 py-3 border rounded-lg"/><input name="password" type="password" minLength={12} required placeholder="Password (12+ characters)" className="w-full px-4 py-3 border rounded-lg"/><label className="flex gap-2 text-sm"><input name="consent" type="checkbox" required/> I consent to creation and processing of my Alvis customer account.</label><button disabled={nav.state==='submitting'} className="w-full bg-purple-600 text-white py-3 rounded-lg font-bold">{nav.state==='submitting'?'Creating…':'Create account'}</button></Form><p className="mt-6 text-sm">Already have an account? <Link to="/auth/login" className="text-purple-600">Sign in</Link></p></AuthLayout>}
